# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

# Mandrill Emailing
MANDRILL_USERNAME: "neil.mithipati@gmail.com"
MANDRILL_APIKEY: "wZS-F4grNHQKL2sOTbOuKA"

# Meme Generator API Key
MEME_APIKEY: "LZM6dmtXNY1xID13rbzVzvGQatYtR0Js"

# Amazon Web Services - S3
AS3_ACCESS_KEY: "AKIAICYMECB6UX3ECIIA"
AS3_SECRET_ACCESS_KEY: "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"
AS3_BUCKET_NAME: "lingo-app"
